-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.certificates
(
    id serial NOT NULL,
    response_id integer,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    filepath character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT certificates_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.question_options
(
    id serial NOT NULL,
    question_id integer,
    value character varying(100) COLLATE pg_catalog."default" NOT NULL,
    text character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT question_options_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.questions
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    required boolean,
    text character varying(500) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    multiple_choice boolean,
    file_format character varying(20) COLLATE pg_catalog."default",
    max_file_size integer,
    max_file_size_unit character varying(5) COLLATE pg_catalog."default",
    multiple_files boolean,
    CONSTRAINT questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.responses
(
    id serial NOT NULL,
    full_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    email_address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    gender character varying(20) COLLATE pg_catalog."default" NOT NULL,
    programming_stack character varying(500) COLLATE pg_catalog."default" NOT NULL,
    date_responded timestamp without time zone NOT NULL,
    CONSTRAINT responses_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.certificates
    ADD CONSTRAINT certificates_response_id_fkey FOREIGN KEY (response_id)
    REFERENCES public.responses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.question_options
    ADD CONSTRAINT question_options_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;